<?php


namespace Tati\TareaFaq\Model;


use Magento\Ui\DataProvider\AbstractDataProvider;

class DataProvider extends AbstractDataProvider
{
    /**
     * Get data
     *
     * @return array
     */
    public function getData()
    {
        return [];
        //return parent::getData(); // TODO: Change the autogenerated stub
    }
}
