<?php


namespace Unit4\PetModel\Model;


use Magento\Framework\DataObject\IdentityInterface;
use Magento\Framework\Model\AbstractModel;

class ModelPet extends AbstractModel implements IdentityInterface
{

    const CACHE_TAG = 'mageplaza_helloworld_post';

    protected $_cacheTag = 'mageplaza_helloworld_post';

    protected $_eventPrefix = 'mageplaza_helloworld_post';

    protected function _construct()
    {
        //parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('\Unit4\PetModel\Model\ResourceModel\Pet');

    }

    public function getIdentities()
    {
        return [self::CACHE_TAG . '_' . $this->getId()];
    }

    //no tengo informacion, preguntar a david
    public function getDefaultValues()
    {
        $values = [];
        return $values;
    }
}
